language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  ## Packages
  - sudo apt-get -qq update > /dev/null
  ## Composer
  - composer self-update
  - composer install --prefer-source --dev
  - phpenv global "$TRAVIS_PHP_VERSION"

script:
  ## PHP_CodeSniffer
  - ./vendor/bin/phpcs --report-width=200 --report-summary  --report-full Classes/ unitTests/ --standard=PSR2 -n
  ## PHPUnit
  - phpunit -c ./unitTests/

notifications:
  email: false
